### PR TITLE
Add cancelable SQL api requests

### PR DESCRIPTION
**Pull request by VictorVelarde**
Add cancelable mechanism to SQL api / datasets fetch requests + its application to:

- [x] Formula widget
- [x] Category widget
- [x] Histogram widget
- [x] Geocoding
- [x] Isochrone
- [x] User datasets

Allow the use of signal & AbortController to abort fetch requests, so they are correctly cleaned up in react components, and they don't throw errors on console like this one:
image

This adds cleanup functions to each component.

### CODE REVIEW

**Comment by VictorVelarde** [comment]
More work is required, either here or in a 2nd PR, for other widgets: Geocoder & Isochrones

**Comment by VictorVelarde** [comment]
I have decided to add more fixes into this PR, related to other models... WIP

**Comment by VictorVelarde** [comment]
NOTE: to avoid similar issues in the future, let's remember always to inject the signal into our new functions inside useEffect (the ones that eventually hit the SQL API).

**Comment by Josmorsot** [comment]
Would be possible to have create the `AbortController` in the executeSQL?

I think that would be great returning an object as {'request': Promise, 'cancel': Function} instead to create it in each widget

**Comment by VictorVelarde** [comment]
Hi @Josmorsot, about your comments... I see your point. 

I've been thinking about it but I'm not sure about making the change, because of the impact to the API. I would like to have more feedback from other mates before we decided:

Here it is the choice:

Option 1 (current: external abort)

client (react component)
```js
useEffect(() => {
    const abortController = new AbortController();
    const signal = abortController.signal;

    const handleCalculateIsochrone = async () => {
      try {
        const isochrone = await getIsochrone(
          credentials,
          {
            geom: latLong,
            mode: selectedMode,
            range: selectedRange,
          },
          { signal }
        );
        updateIsochrone(isochrone);
      } catch (error) {
        if (error.name === 'AbortError') return;

        dispatch(setError(`Isochrone error: ${error.message}`));
      }
    };

    return function cleanup() {
      abortController.abort();
    };
  });
```

Option 2 (internal abort)

```js
 useEffect(() => {
    let getIsochroneRequest;
    const handleCalculateIsochrone = async () => {
      try {
        getIsochroneRequest = await getIsochrone(
          credentials,
          {
            geom: latLong,
            mode: selectedMode,
            range: selectedRange,
          }
        );

        const isochroneResult = await getIsochroneRequest.result;
        updateIsochrone(isochroneResult);
      } catch (error) {
        if (error.name === 'AbortError') return;

        dispatch(setError(`Isochrone error: ${error.message}`));
      }
    };

    return function cleanup() {
      getIsochroneRequest.cancel();
    };
  });
```

On the one hand, option 1 (current) keeps the abort mechanism as something optional, and controlled by the client, keeping the api responses more simple for non cancelable use cases...

On the other hand, option 2 works probably better as an abstraction for cancelable use cases, but at the cost of adding always this kind of response object for all api requests:

```
// made-up, not real SQL api
export const apiRequest = async (opts) => {
    const abortController = new AbortController();
    const signal = abortController.signal;

    let promise = fetch(request, { signal } );
 
    return {
          result: promise,
          cancel: () => { abortController.abort() }
    }
};
```

**Comment by alasarr** [comment]
I'd go with something like this:
```javascript
useEffect(() => {
    const abortController = new AbortController();

    const handleCalculateIsochrone = async () => {
      try {
        const isochrone = await getIsochrone(
          credentials,
          {
            geom: latLong,
            mode: selectedMode,
            range: selectedRange,
          },
          { abortController }
        );
        updateIsochrone(isochrone);
      } catch (error) {
        if (error.name === 'AbortError') return;

        dispatch(setError(`Isochrone error: ${error.message}`));
      }
    };

    return function cleanup() {
      abortController.abort();
    };
  });

**Comment by VictorVelarde** [comment]
Need to reopen, as I forced reset with develop for the sync

**Comment by VictorVelarde** [comment]
Need to create a different PR with same branch

**Review by alasarr — CHANGES_REQUESTED** [review]
We need to add the abort to StoresDetail and the models: StoreModel and IsochroneModel

**Review by alasarr — APPROVED** [review]

**Pull request merged**
